server {
    listen 54321;
    listen [::]:54321;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /data.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        expires -1;
    }

    location ~* \.(?:css|js)$ {
        expires 1h;
        add_header Cache-Control "public, max-age=3600";
    }

    location ~ /\. {
        deny all;
    }
}
